### PR TITLE
Add version string, make executable

### PR DESCRIPTION
**Pull request by grembo**
Also add little text linking to the project to give feedback.
Correct tab vs spaces issue that messed with usage.

@bretton Maybe a quick test can't hurt. Should we keep tracing changes within the script (maybe a separate changelog would make more sense at some point).

### CODE REVIEW

**Comment by bretton** [comment]
tests fine, boots, can login

**Comment by grembo** [comment]
Thanks. Output also ok?

**Comment by bretton** [comment]
screenshot2

**Comment by grembo** [comment]
thanks.

**Pull request merged**
