### PR TITLE
Check if kvm is supported before passing in flags requiring it

### LINKED ISSUE #17: qemu won't run on servers that don't have virtualization support
Subj.
I have a server with an Intel Atom processor where there is no virtualization support.

Therefore, instead of the mandatory qemu options (  `-enable-kvm`  `-cpu host` ), you need to check for virtualization support.

### PR DESCRIPTION
**Pull request by grembo**
Completely untested

Fixes #17

### CODE REVIEW

**Comment by grembo** [comment]
@click0 Can you test this on your atom machine? (and potentially on a machine that *should* support kvm/hw virtualization?)

**Comment by click0** [comment]
> @click0 Can you test this on your atom machine? (and potentially on a machine that _should_ support kvm/hw virtualization?)

There is no way to restart the machine, it is in operation mode.
From the recovery action log in risk mode, there is a qemu startup line:

`/tmp/qemu-system-x86_64 -net nic -net user,hostfwd=tcp::3389-:3389,hostfwd=tcp::1022-:1022  -m 2600M -localtime  -M pc -smp 3 -vga std -usbdevice tablet -k en-us -hda /dev/sda  -boot once=d -vnc :1 &`

**Comment by grembo** [comment]
@bretton So I guess we'll just test if this works for machines that have hw virtualization, and if it does, commit it (as it won't make things worse in this case). We definitely need a file to track tested configurations within the repo (outside of issues, but supported by issues).

**Comment by grembo** [comment]
@click0 Thanks for you valuable feedback (not just on this issue)

**Comment by bretton** [comment]
test works with with default options and key. login works fine.

script shows output of kvm-ok before starting qemu

**Pull request merged**
