### PR TITLE
Make authorized_keys optional when `-m URL` is given

### LINKED ISSUE #16: I need to use password access to MfsBSD
A vanilla build of MfsBSD with root password is enough for me.
The mandatory requirement to use ssh keys is superfluous.

### PR DESCRIPTION
**Pull request by grembo**
People might create images without any kind of security requirements,
so lets give them the freedom to do whatever works for them.

Fixes #16

### CODE REVIEW

**Comment by grembo** [comment]
@click0 Can you try if this works for you? (as it's untested)

**Comment by click0** [comment]
Probably should use `${REQUIRE_SSHKEY}` instead of `$REQUIRE_SSHKEY`.

**Comment by grembo** [comment]
> Probably should use `${REQUIRE_SSHKEY}` instead of `$REQUIRE_SSHKEY`.

Doesn't make a difference in this context (only would if we wrote `"${REQUIRE_SSHKEY}sometext"`). I'll spare you from quoting random stackoverflow answers on that particular issue :D

**Comment by grembo** [comment]
> > Probably should use `${REQUIRE_SSHKEY}` instead of `$REQUIRE_SSHKEY`.
> 
> Doesn't make a difference in this context (only would if we wrote `"${REQUIRE_SSHKEY}sometext"`). I'll spare you from quoting random stackoverflow answers on that particular issue :D

@click0 But this made me open #19

**Comment by bretton** [comment]
Testing without key on custom image boots fine, ssh is live, can't login, no password set on the ISO used

**Pull request merged**
